# 공통 설정
spring:
  profiles:
      active: dev
  jpa:
    open-in-view: true
    hibernate:
      # create : 실행할 때마다 테이블을 drop 하고 다시 생성
      ddl-auto: create
    # 로그에 sql 문을 출력
    show-sql: true
    properties:
      # 로그에 sql 문을 formatting 해서 출력
      hibernate.format_sql: true

---

# 개발환경 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/escape?serverTimezone=Asia/Seoul
    username: root
    password: 1234

---

# 운영환경 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
